source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'MWPhotoBrowser_Example' do
  pod "MWPhotoBrowser", :path => "../"
#  pod "SDWebImage/WebP"
end

target 'MWPhotoBrowser_Tests' do
  pod "MWPhotoBrowser", :path => "../"

  # pod 'Specta'
  # pod 'Expecta'
  # pod 'FBSnapshotTestCase'
  # pod 'Expecta+Snapshots'
end
